version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram-client-php
    volumes:
      # Only mount source files, not vendor directory
      - ./src:/var/www/html/src
      - ./console-examples.php:/var/www/html/console-examples.php
      - ./index.php:/var/www/html/index.php
      - ./README.md:/var/www/html/README.md
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
    restart: unless-stopped
